# Generated by Django 3.2.8 on 2021-11-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("picture", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(editable=False)),
                ("session_date", models.DateTimeField(editable=False)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("I", "Insert"), ("D", "Delete"), ("U", "Update")],
                        editable=False,
                        max_length=1,
                    ),
                ),
                ("object_id", models.BigIntegerField(editable=False)),
                ("snapshot", models.JSONField(blank=True, editable=False, null=True)),
                ("changes", models.JSONField(blank=True, editable=False, null=True)),
                ("username", models.TextField()),
                ("extra", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_history",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="testapp.Author"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="customhistory",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="custom_hist_content_09c971_idx",
            ),
        ),
    ]
